version: '3.8'

services:
  # my-app:
  #   container_name: my-app
  #   build: ./
  #   restart: unless-stopped
  #   ports:
  #     - 4000:4000
  #   networks:
  #     - mynet

  db:
    container_name: grab_db
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: grabber
    networks:
      - mynet
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data

networks:
  mynet:
    driver: bridge