version: '3'

services:
  app:
    container_name: grabber-app_web
    build: ./
    restart: unless-stopped
    ports:
      - 4001:4001
    environment:
      APP_PORT: 4001
      PG_USER: postgres
      PG_PASSWORD: secret
      PG_DATABASE: grabber
      PG_HOST: grab_db_web
      PG_PORT: 5432
    volumes:
      - ./volumes/logs:/app/logs
      - ./volumes/files:/app/files
    networks:
      - mynet
      - malone_7

  db:
    container_name: grab_db_web
    image: postgres:15-alpine
    ports:
      - "5435:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: grabber
    networks:
      - mynet
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data

networks:
  mynet:
    driver: bridge
  malone_7:
    external: true